###Root URL
GET http://localhost:9000/ HTTP/1.1

###Get all Products 
GET http://localhost:9000/products HTTP/1.1

###Add a new product
POST http://localhost:9000/addProduct HTTP/1.1
content-type: application/json

{
    "productCategory": "Mouse",
    "productSubCategory": "wired mouse",
    "productDiscription":"Wired mouse",
    "availableStock":100
}

###Add a new product
POST http://localhost:9000/getProductWhere HTTP/1.1
content-type: application/json

{
    "productCategory": "Keyboard",
    "availableStock":100
}